services:
  balancer:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
  backend1:
    image: hashicorp/http-echo
    command: [ "-text=backend1", "-listen=:8081" ]
    ports: [ "8081:8081" ]
  backend2:
    image: hashicorp/http-echo
    command: [ "-text=backend2", "-listen=:8082" ]
    ports: [ "8082:8082" ]